import { Member, Expense } from '../types';

export const mapMemberToDb = (member: Partial<Member>) => ({
  id: member.id,
  user_group_id: member.userGroupId,
  auth_user_id: member.authUserId,
  role: member.role,
  full_name: member.fullName,
  nickname: member.nickname,
  username: member.username,
  gender: member.gender,
  email: member.email,
  phone: member.phone,
});

export const mapMemberFromDb = (dbMember: any): Member => ({
  id: dbMember.id,
  userGroupId: dbMember.user_group_id,
  authUserId: dbMember.auth_user_id,
  role: dbMember.role,
  fullName: dbMember.full_name,
  nickname: dbMember.nickname,
  username: dbMember.username,
  gender: dbMember.gender,
  email: dbMember.email,
  phone: dbMember.phone,
});

export const mapExpenseToDb = (expense: Partial<Expense>) => ({
  id: expense.id,
  user_group_id: expense.userGroupId,
  description: expense.description,
  amount: expense.amount,
  date: expense.date,
  type: expense.type,
  payer_id: expense.payerId,
  payment_method: expense.paymentMethod,
  payment_type: expense.paymentType,
  installments: expense.installments,
  installment_day: expense.installmentDay,
  installment_start_month: expense.installmentStartMonth,
  installment_number: expense.installmentNumber,
  is_recurring: expense.isRecurring,
  recurring_day: expense.recurringDay,
  status_a: expense.statusA,
  status_b: expense.statusB,
  parent_id: expense.generatedFromId,
});

export const mapExpenseFromDb = (dbExpense: any): Expense => ({
  id: dbExpense.id,
  userGroupId: dbExpense.user_group_id,
  description: dbExpense.description,
  amount: Number(dbExpense.amount),
  date: dbExpense.date,
  type: dbExpense.type,
  payerId: dbExpense.payer_id,
  paymentMethod: dbExpense.payment_method,
  paymentType: dbExpense.payment_type,
  installments: dbExpense.installments,
  installmentDay: dbExpense.installment_day,
  installmentStartMonth: dbExpense.installment_start_month,
  installmentNumber: dbExpense.installment_number,
  isRecurring: dbExpense.is_recurring,
  recurringDay: dbExpense.recurring_day,
  statusA: dbExpense.status_a,
  statusB: dbExpense.status_b,
  generatedFromId: dbExpense.parent_id,
  created_at: dbExpense.created_at,
});
